# Generated by Django 5.2.10 on 2026-01-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Для красивых ссылок: /category/rozy', max_length=140, unique=True, verbose_name='URL-slug')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL-slug')),
                ('description', models.TextField(blank=True, help_text='Состав, особенности, как ухаживать', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Цена в копейках. 150000 = 1500₽', verbose_name='Цена (копейки)')),
                ('old_price', models.PositiveIntegerField(blank=True, help_text='Для отображения скидки. Оставить пустым если нет скидки', null=True, verbose_name='Старая цена (копейки)')),
                ('qty_available', models.PositiveIntegerField(default=0, verbose_name='В наличии')),
                ('is_unlimited', models.BooleanField(default=False, help_text='Если True — товар всегда доступен', verbose_name='Под заказ (неограничено)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Для SEO и доступности', max_length=160, verbose_name='Alt-текст')),
                ('is_main', models.BooleanField(db_index=True, default=False, verbose_name='Главное фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['-is_main', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'sort_order'], name='products_pr_is_acti_779f60_idx'),
        ),
    ]
