# Generated by Django 5.2.10 on 2026-01-16 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('in_progress', 'Готовится'), ('delivering', 'Доставляется'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], db_index=True, default='new', max_length=24, verbose_name='Статус')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Сумма товаров (копейки)')),
                ('delivery_fee', models.PositiveIntegerField(default=0, verbose_name='Стоимость доставки (копейки)')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка (копейки)')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Итого (копейки)')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Имя получателя')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('delivery_comment', models.TextField(blank=True, help_text='Домофон, подъезд, особые пожелания', verbose_name='Комментарий')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_time_from', models.TimeField(blank=True, null=True, verbose_name='Время с')),
                ('delivery_time_to', models.TimeField(blank=True, null=True, verbose_name='Время до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product_title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Цена за единицу (копейки)')),
                ('line_total', models.PositiveIntegerField(verbose_name='Сумма позиции (копейки)')),
                ('image_url', models.URLField(blank=True, help_text='Snapshot фото на момент заказа', max_length=500, verbose_name='URL фото')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
