# Generated by Django 5.2.10 on 2026-01-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('link_after_order', 'Ссылка на оплату после заказа')], default='link_after_order', max_length=32, verbose_name='Способ оплаты'),
        ),
    ]
